### ISSUE TITLE
Sample Scan Template Files Need For Unit Test

### ISSUE THREAD

**Issue by propersam** [DefectDojo/sample-scan-files#23]
Hello @aaronweaver @mtesauro

I and @Maffooch are working on implementing Unit Test for Import Scanners on the DefectDojo Project.

In order to complete this task, we need to store on this repo all sample scan files of all scanners in https://github.com/DefectDojo/django-DefectDojo/tree/master/dojo/tools

we have been able to get some of the missing sample scan files but the following underlisted are no where to be found.

[ ] appspider
[ ] aws_prowler
[ ] aws_scout2
[ ] fortify
[ ] mobsf
[ ] openvas_csv
[ ] qualys (In repo already : https://github.com/DefectDojo/sample-scan-files/tree/master/qualys)
[x] retirejs (In repo now : Maffooch)
[ ] skf
[ ] spotbugs
[ ] trustwave
[ ] vcg

Is there any way their sample scan files can be fetched and uploaded here so they can be added to the repo.

**Comment by propersam** [comment]
Some of the parsers of the above scan tools have an `author` field added but i'm not sure how to reach out to them. 

@aaronweaver is in most of them either as an author or a guide. So I guess he should at least have some pointers on how we can get the above requested scan files.

**Comment by Maffooch** [comment]
Ive got a Retire.JS Ill push to the repo in just a few

**Comment by propersam** [comment]
I see retireJs has now been added..

**Comment by propersam** [comment]
Completing this sample files are really taking longer than i expected.

Can i go on to create some custom files by reverse engineering the parsers...

**Comment by propersam** [comment]
it will definitely be a rough sketch/precision..nd not like the standard scan files...but our Import Scanner unit test will proceed..
