### ISSUE TITLE
Veracode static and dynamic sample scan is out of date.

### ISSUE THREAD

**Issue by minton55** [DefectDojo/sample-scan-files#72]
Trying to import the [sample Veracode static and dynamic scan](https://github.com/DefectDojo/sample-scan-files/blob/master/veracode/veracode.Sample_Static_and_Dynamic.xml) fails with an import error. "An error has occurred in the parser, please see error log for details."  I believe this sample may be out of date as existing Veracode scans that I get directly from Veracode parse without problem.

This is also true for [sample Veracode scan](https://github.com/DefectDojo/sample-scan-files/blob/master/veracode/veracode_scan.xml)

I am running DefectDojo-Django in Docker.
v. 1.12.0 ( release mode )

**Comment by valentijnscholten** [comment]
Do you have an example that you could share (in a PR) here to update our sample to a more current one?

**Comment by minton55** [comment]
Unfortunately, all of the ones that I have I am not allowed to share.

**Comment by damiencarol** [comment]
@minton55 could you at least produce a stack trace?
